controller_server:
  ros__parameters:
    controller_frequency: 15.0
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"] #, "precise_goal_checker"] 
    controller_plugins: ["FollowPath"]
    # current_goal_checker: "general_goal_checker"

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.1
      movement_time_allowance: 10.0
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.250
      yaw_goal_tolerance: 0.250
    precise_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.50
      yaw_goal_tolerance: 0.50
    

    # my DWB parameters 
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: false
      min_vel_x: 0.09
      min_vel_y: 0.01
      max_vel_x: 1.7
      max_vel_y: 1.7
      max_vel_theta: 0.8
      min_speed_xy: 0.0
      max_speed_xy: 1.7
      min_speed_theta: 0.0
      acc_lim_x: 1.8
      acc_lim_y: 1.5
      acc_lim_theta: 0.80
      decel_lim_x: -2.5
      decel_lim_y: -2.5
      decel_lim_theta: -5.0
      vx_samples: 60
      vy_samples: 40
      vtheta_samples: 30
      sim_time: 1.7
      linear_granularity: 0.5
      angular_granularity: 0.52
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True

      # publish_cost_grid_pc: True

      stateful: True
      critics: ["RotateToGoal", "ObstacleFootprint", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle:scale: 0.02
      PathAlign.scale: 50.0
      PathAlign.forward_point_distance: 0.5
      GoalAlign.scale: 5.0
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 5.0
      RotateToGoal.scale: 10.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0
      ObstacleFootprint.scale: 5.0


local_costmap:
  local_costmap:
    ros__parameters:
      qos_overrides:
        subscription:
          durability: VOLATILE
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: robot/odom
      robot_base_frame: robot/base_link
      use_sim_time: True
      rolling_window: true
      width: 10
      height: 10
      resolution: 0.06
      robot_radius: 0.2
      plugins: ["static_layer"] # , "inflation_layer"]
      # plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        map_topic: "/map/white"
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: False
        enabled: true
        subscribe_to_updates: true

      # obstacle_layer:
      #   plugin: "nav2_costmap_2d::ObstacleLayer"
      #   enabled: true
      #   observation_sources: scan
      #   pointcloud:
      #     topic: /lidar/points
      #     max_obstacle_height: 2.0
      #     clearing: true
      #     marking: true
      #     data_type: "PointCloud2"
      #     raytrace_max_range: 3.0
      #     raytrace_min_range: 0.0
      #     obstacle_max_range: 2.5
      #     obstacle_min_range: 0.4
      #   scan:
      #     topic: /lidar/scan
      #     max_obstacle_height: 2.0
      #     clearing: True
      #     marking: True
      #     data_type: "LaserScan"
      #     raytrace_max_range: 3.0
      #     raytrace_min_range: 0.0
      #     obstacle_max_range: 2.5
      #     obstacle_min_range: 0.9

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 0.5
        inflation_radius: 0.8
