
planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

global_costmap:
  global_costmap:
    ros__parameters:
      qos_overrides:
        subscription:
          durability: VOLATILE
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      width: 10
      height: 10
      use_sim_time: True
      robot_radius: 0.35
      resolution: 0.04
      track_unknown_space: false
      # plugins: ["static_layer", "obstacle_layer", "inflation_layer"] # , "voxel_layer"]
      plugins: ["static_layer", "inflation_layer"] # , "voxel_layer"]


      static_layer:
        map_topic: "/map/motion_control"
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: False
      # obstacle_layer:
      #   plugin: "nav2_costmap_2d::ObstacleLayer"
      #   enabled: True
      #   observation_sources: pointcloud
      #   scan:
      #     topic: /lidar/scan
      #     max_obstacle_height: 2.0
      #     clearing: True
      #     marking: True
      #     data_type: "LaserScan"
      #     raytrace_max_range: 3.0
      #     raytrace_min_range: 0.0
      #     obstacle_max_range: 2.5
      #     obstacle_min_range: 0.5
      #   pointcloud:
      #     topic: /lidar/points
      #     max_obstacle_height: 2.0
      #     clearing: true
      #     marking: true
      #     data_type: "PointCloud2"
      #     raytrace_max_range: 3.0
      #     raytrace_min_range: 0.0
      #     obstacle_max_range: 2.5
      #     obstacle_min_range: 0.7
      
      # voxel_layer:
      #   plugin: "nav2_costmap_2d::VoxelLayer"
      #   enabled: True
      #   publish_voxel_map: True
      #   origin_z: 0.0
      #   z_resolution: 0.05
      #   z_voxels: 16
      #   max_obstacle_height: 2.0
      #   mark_threshold: 0
      #   observation_sources: pointcloud
      #   pointcloud:
      #     topic: /lidar/points
      #     max_obstacle_height: 2.0
      #     clearing: true
      #     marking: true
      #     data_type: "PointCloud2"
      #     raytrace_max_range: 3.0
      #     raytrace_min_range: 0.0
      #     obstacle_max_range: 2.5
      #     obstacle_min_range: 0.5
      #   scan:
      #     topic: /lidar/scan
      #     max_obstacle_height: 2.0
      #     clearing: True
      #     marking: True
      #     data_type: "LaserScan"
      #     raytrace_max_range: 3.0
      #     raytrace_min_range: 0.0
      #     obstacle_max_range: 2.5
      #     obstacle_min_range: 0.0
      
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 0.5
        inflation_radius: 0.30
      always_send_full_costmap: false
