TebLocalPlannerROS:
  # Trajectory

  odom_topic: odom

  teb_autosize: True
  dt_ref: 0.5
  dt_hysteresis: 0.2
  max_global_plan_lookahead_dist: 2.0
  feasibility_check_no_poses: 4

  # Robot

  max_vel_x: 1.2
  max_vel_x_backwards: 0.3
  max_vel_y: 0.0
  max_vel_theta: 0.2
  acc_lim_x: 1.2
  acc_lim_theta: 0.3
  min_turning_radius: 0.0

  footprint_model:
    type: "point"

  # GoalTolerance

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.5
  free_goal_vel: False

  controller_frequency: 5.0

  # Obstacles

  min_obstacle_dist: 0.45 # This value must also include our robot radius, since footprint_model is set to "point".
  inflation_dist: 0.55
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.5
  include_dynamic_obstacles: True

  # Optimization

  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  obstacle_cost_exponent: 4
  weight_max_vel_x: 100
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 20
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 2 # must be > 0
  weight_shortest_path: 0
  weight_obstacle: 30
  weight_inflation: 50
  weight_dynamic_obstacle: 10
  weight_dynamic_obstacle_inflation: 0.2
  weight_viapoint: 30
  weight_adapt_factor: 2

  # Homotopy Class Planner

  enable_homotopy_class_planning: True
  enable_multithreading: True
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  selection_prefer_initial_plan: 0.9
  selection_obst_cost_scale: 100.0
  selection_alternative_time_cost: False

  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  roadmap_graph_area_length_scale: 1.0
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 0.45
  switching_blocking_period: 0.0
  viapoints_all_candidates: True
  delete_detours_backwards: True
  max_ratio_detours_duration_best_duration: 3.0
  visualize_hc_graph: False
  visualize_with_time_as_z_axis_scale: False