sim: true

detectors:
  enable: true
  mode: 1 # 0 for YOLO, 1 for height (pothole and stop always use YOLO/RGB), 2 for qual
  stop_sign:
    text: "STOP"

goal_calculator:
  enable: true # for goal calculators

behaviour_manager: # for automated actions
  enable: true
  code: 0
