    # my MPPI PARAMETERS
    # FollowPath:
    #   plugin: "nav2_mppi_controller::MPPIController"
    #   time_steps: 56
    #   model_dt: 0.5
    #   batch_size: 1000
    #   vx_std: 0.2
    #   vy_std: 0.2
    #   wz_std: 0.4
    #   vx_max: 0.26
    #   vx_min: -0.26
    #   vy_max: 0.26
    #   wz_max: 1.9
    #   wz_min: -1.9
    #   # ax_max: 3.0
    #   # ax_min: -3.0
    #   # ay_max: 3.0
    #   # az_max: 3.5
    #   iteration_count: 1
    #   prune_distance: 1.7
    #   transform_tolerance: 0.3
    #   temperature: 0.3
    #   gamma: 0.015
    #   motion_model: "DiffDrive"
    #   visualize: false
    #   reset_period: 1.0
    #   regenerate_noises: False

    #   critics:
    #     ConstraintCritic:
    #       enabled: true
    #       cost_power: 1
    #       cost_weight: 4.0
    #     GoalCritic:
    #       enabled: true
    #       cost_power: 1
    #       cost_weight: 5.0
    #       threshold_to_consider: 1.4
    #     GoalAngleCritic:
    #       enabled: true
    #       cost_power: 1
    #       cost_weight: 3.0
    #       threshold_to_consider: 0.5
    #     PreferForwardCritic:
    #       enabled: true
    #       cost_power: 1
    #       cost_weight: 5.0
    #       threshold_to_consider: 0.5
    #     CostCritic:
    #       enabled: true
    #       cost_power: 1
    #       cost_weight: 3.81
    #       critical_cost: 300.0
    #       consider_footprint: true
    #       collision_cost: 1000000.0
    #       near_goal_distance: 1.0
    #       trajectory_point_step: 2
    #     PathAlignCritic:
    #       enabled: true
    #       cost_power: 1
    #       cost_weight: 14.0
    #       max_path_occupancy_ratio: 0.05
    #       trajectory_point_step: 4
    #       threshold_to_consider: 0.5
    #       offset_from_furthest: 20
    #       use_path_orientations: false
    #     PathFollowCritic:
    #       enabled: true
    #       cost_power: 1
    #       cost_weight: 5.0
    #       offset_from_furthest: 5
    #       threshold_to_consider: 1.4
    #     PathAngleCritic:
    #       enabled: true
    #       cost_power: 1
    #       cost_weight: 2.0
    #       offset_from_furthest: 4
    #       threshold_to_consider: 0.5
    #       max_angle_to_furthest: 1.0
    #       mode: 0
    #     TwirlingCritic:
    #       enabled: true
    #       twirling_cost_power: 1
    #       twirling_cost_weight: 10.0

    #   # # critics: ["ConstraintCritic", "ObstaclesCritic", "GoalCritic", "GoalAngleCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic", "PathAlignCritic"]
    #   #   ConstraintCritic:
    #   #     enabled: true
    #   #     cost_power: 1
    #   #     cost_weight: 2.0
    #   #   GoalCritic:
    #   #     enabled: true
    #   #     cost_power: 4
    #   #     cost_weight: 10.0
    #   #     threshold_to_consider: 1.5
    #   #   GoalAngleCritic:
    #   #     enabled: true
    #   #     cost_power: 4
    #   #     cost_weight: 3.0
    #   #     threshold_to_consider: 1.5
    #   #   PreferForwardCritic:
    #   #     enabled: true
    #   #     cost_power: 1
    #   #     cost_weight: 2.0
    #   #     threshold_to_consider: 1.5
    #   #   ObstaclesCritic:
    #   #     enabled: true
    #   #     cost_power: 1
    #   #     repulsion_weight: 1.0
    #   #     critical_weight: 20.0
    #   #     consider_footprint: true
    #   #     collision_cost: 10000.0
    #   #     collision_margin_distance: 0.05
    #   #     near_goal_distance: 0.5
    #   #   PathAlignCritic:
    #   #     enabled: true
    #   #     cost_power: 1
    #   #     cost_weight: 14.0
    #   #     max_path_occupancy_ratio: 0.05
    #   #     trajectory_point_step: 3
    #   #     threshold_to_consider: 0.5
    #   #     offset_from_furthest: 20
    #   #     use_path_orientations: false
    #   #   PathFollowCritic:
    #   #     enabled: true
    #   #     cost_power: 1
    #   #     cost_weight: 5.0
    #   #     offset_from_furthest: 5
    #   #     threshold_to_consider: 1.4
    #   #   PathAngleCritic:
    #   #     enabled: true
    #   #     cost_power: 1
    #   #     cost_weight: 2.0
    #   #     offset_from_furthest: 4
    #   #     threshold_to_consider: 0.5
    #   #     max_angle_to_furthest: 1.0
    #   #     forward_preference: true
    #   #   TwirlingCritic:
    #   #     enabled: true
    #   #     twirling_cost_power: 1
    #   #     twirling_cost_weight: 10.0


# DWB parameters Online
    # FollowPath:
    #   plugin: "dwb_core::DWBLocalPlanner"
    #   debug_trajectory_details: True
    #   min_vel_x: -0.26
    #   min_vel_y: -0.26
    #   max_vel_x: 0.26
    #   max_vel_y: 0.26
    #   max_vel_theta: 2.0
    #   min_speed_xy: 0.0
    #   max_speed_xy: 0.26
    #   min_speed_theta: 0.0
    #   acc_lim_x: 0.5
    #   acc_lim_y: 0.5
    #   acc_lim_theta: 0.5
    #   decel_lim_x: -0.5
    #   decel_lim_y: -0.5
    #   decel_lim_theta: -0.5
    #   vx_samples: 20
    #   vy_samples: 5
    #   vtheta_samples: 20
    #   sim_time: 1.7
    #   linear_granularity: 0.05
    #   angular_granularity: 0.025
    #   transform_tolerance: 0.2
    #   xy_goal_tolerance: 0.25
    #   trans_stopped_velocity: 0.25
    #   short_circuit_trajectory_evaluation: True
    #   stateful: True
    #   footprint: "[ [0.305, 0.298], [0.305, -0.298], [-0.305, -0.298], [-0.305, 0.298] ]"
    #   critics: ["RotateToGoal", "Oscillation", "GoalAlign", "PathAlign", "PathDist", "GoalDist", "ObstacleFootprint"]
    #   #BaseObstacle.scale: 0.02
    #   PathAlign.scale: 32.0
    #   PathAlign.forward_point_distance: 0.1
    #   GoalAlign.scale: 24.0
    #   GoalAlign.forward_point_distance: 0.1
    #   PathDist.scale: 32.0
    #   GoalDist.scale: 24.0
    #   RotateToGoal.scale: 32.0
    #   RotateToGoal.slowing_factor: 5.0
    #   RotateToGoal.lookahead_time: -1.0


###Online MPPI at ###
# https://robotics.stackexchange.com/questions/107807/ros2-robot-wont-move-sideways-with-dwb-or-mppi-controllers
#  controller_server:
#   ros__parameters:
#     use_sim_time: True
#     controller_frequency: 10.0
#     min_x_velocity_threshold: 0.001
#     min_y_velocity_threshold: 0.5
#     min_theta_velocity_threshold: 0.001
#     failure_tolerance: 0.3
#     progress_checker_plugin: "progress_checker"
#     goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
#     controller_plugins: ["FollowPath"]

#     # Progress checker parameters
#     progress_checker:
#       plugin: "nav2_controller::SimpleProgressChecker"
#       required_movement_radius: 0.5
#       movement_time_allowance: 10.0
#     general_goal_checker:
#       stateful: True
#       plugin: "nav2_controller::SimpleGoalChecker"
#       xy_goal_tolerance: 0.25
#       yaw_goal_tolerance: 0.25

#     FollowPath:
#       plugin: "nav2_mppi_controller::MPPIController"
#       time_steps: 56
#       model_dt: 0.1
#       batch_size: 2000
#       vx_std: 0.2
#       vy_std: 0.2
#       wz_std: 0.4
#       vx_max: 0.26
#       vx_min: -0.26
#       vy_max: 0.26
#       wz_max: 1.9
#       wz_min: -1.9
#       iteration_count: 1
#       prune_distance: 1.7
#       transform_tolerance: 0.1
#       temperature: 0.3
#       gamma: 0.015
#       motion_model: "DiffDrive"
#       visualize: true
#       TrajectoryVisualizer:
#         trajectory_step: 5
#         time_step: 3
#       critics: ["ConstraintCritic", "ObstaclesCritic", "GoalCritic", "GoalAngleCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic", "PathAlignCritic"]
#       ConstraintCritic:
#         enabled: true
#         cost_power: 1
#         cost_weight: 2.0
#       GoalCritic:
#         enabled: true
#         cost_power: 4
#         cost_weight: 10.0
#         threshold_to_consider: 1.5
#       GoalAngleCritic:
#         enabled: true
#         cost_power: 4
#         cost_weight: 3.0
#         threshold_to_consider: 1.5
#       PreferForwardCritic:
#         enabled: true
#         cost_power: 1
#         cost_weight: 2.0
#         threshold_to_consider: 1.5
#       ObstaclesCritic:
#         enabled: true
#         cost_power: 1
#         repulsion_weight: 1.0
#         critical_weight: 20.0
#         consider_footprint: true
#         collision_cost: 10000.0
#         collision_margin_distance: 0.05
#         near_goal_distance: 0.5
#       PathAlignCritic:
#         enabled: true
#         cost_power: 1
#         cost_weight: 14.0
#         max_path_occupancy_ratio: 0.05
#         trajectory_point_step: 3
#         threshold_to_consider: 0.5
#         offset_from_furthest: 20
#         use_path_orientations: false
#       PathFollowCritic:
#         enabled: true
#         cost_power: 1
#         cost_weight: 5.0
#         offset_from_furthest: 5
#         threshold_to_consider: 1.4
#       PathAngleCritic:
#         enabled: true
#         cost_power: 1
#         cost_weight: 2.0
#         offset_from_furthest: 4
#         threshold_to_consider: 0.5
#         max_angle_to_furthest: 1.0
#         forward_preference: true
#       TwirlingCritic:
#         enabled: true
#         twirling_cost_power: 1
#         twirling_cost_weight: 10.0

# controller_server_rclcpp_node:
#   ros__parameters:
#     use_sim_time: True

