TebLocalPlannerROS:
  # Trajectory
  teb_autosize: True
  dt_ref: 0.4
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: True
  allow_init_with_backwards_motion: False
  max_global_plan_lookahead_dist: 1.5
  feasibility_check_no_poses: 5

  # Robot
  max_vel_x: 2.3
  max_vel_x_backwards: 0.4
  max_vel_y: 0.0 # For a differential drive robot
  max_vel_theta: 0.5
  acc_lim_x: 2.0
  acc_lim_y: 0.0 # For a differential drive robot
  acc_lim_theta: 1.0
  min_turning_radius: 0.0

  footprint_model:
    type: "point"

  # Goal Tolerance
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  free_goal_vel: False

  # Obstacles
  min_obstacle_dist: 0.45
  inflation_dist: 0.5
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30
  dynamic_obstacle_inflation_dist: 0.6
  include_dynamic_obstacles: True
  predict_obstacles: True

  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  # weight_max_vel_x: 50.0
  # weight_max_vel_theta: 20.0
  # weight_acc_lim_x: 50.0
  # weight_acc_lim_theta: 10.0
  weight_kinematics_nh: 1000.0 # Non-holonomic kinematics weight
  # weight_kinematics_forward_drive: 30.0
  # weight_optimaltime: 40.0
  # weight_obstacle: 50.0
  # weight_inflation: 40.0
  # weight_viapoint: 30.0

  # Homotopy Class Planning
  enable_homotopy_class_planning: True
  enable_multithreading: True
  simple_exploration: False
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5.0
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  visualize_hc_graph: False

  # Miscellaneous
  global_plan_prune_distance: 1.0
